import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
=======
import Link from "next/link";
import About from "./about/page";
>>>>>>> new-branch

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
<<<<<<< HEAD
      {children}
=======
      <header>
      <nav className="flex w-full bg-black h-32 items-center text-3xl font-serif">
        <Link href="/" className="bg-orange-400 h-10 w-96 ml-5  font-bold text-center text- text-white hover:mt-2 hover:cursor-pointer">HASSAN_ALi</Link>

        <div className="flex justify-end w-3/5 items-center gap-2 ml-12">
        <Link href="home" className="bg-orange-400 h-10 w-44 font-bold text-center text-white hover:mt-2 hover:cursor-pointer">Home</Link>
        <Link href="about" className="bg-orange-400 h-10 w-44 font-bold text-center text-white hover:mt-2 hover:cursor-pointer">About</Link>
        <Link href="projects" className="bg-orange-400 h-10 w-44 font-bold text-center text-white hover:mt-2 hover:cursor-pointer">Projects</Link>
        <Link href="contact" className="bg-orange-400 h-10 w-44 font-bold text-center text-white hover:mt-2 hover:cursor-pointer">Contact</Link>
          {/* <div className="bg-orange-400 h-10 w-44 font-bold text-center text-white hover:mt-2 hover:cursor-pointer">Contact</div> */}
        </div>
      
      </nav>
      </header>
      {children}
      <footer className="mt-auto text-center text-2xl">
         {/* Footer  */}
      <div className="mt-auto text-center text-4xl">
        <p className="text-black">Footer or additional content</p>
      </div>
      </footer>
>>>>>>> new-branch
    </body>
  </html>
  );
}
